[Server]
Addr = "127.0.0.1"
Port = "9998"
LogPath = "/tmp/auth.log"

[MySQL]
DSN = "root:abcd1234@tcp(127.0.0.1:3306)/test"
Idle = 10
Active = 10
IdleTimeout = 400

[Redis]
Host = "127.0.0.1"
Port = "6379"
MaxIdle = 10
MaxActive = 10
IdleTimeout = 400
MaxConnLifetime = 400
